		</div>
		
		<div id="footer" class="">
			<h4>LOTUS SRL</h4>
			<p>Viale della Regione Veneto, 16 - 35127 Padova, Italy   /   Tel. +39.049.8705345/8705370   /   Fax +39.049.8705091   /   Email: <a href="mailto:info@lotuspd.com">info@lotuspd.com</a></p>
			<p>CF-PI_Iscr.Reg.Imp.: PADOVA 03668200284   /   REA: PD 327519   /   Cap. Soc. euro 99.000,00 i.v.</p>
		</div>	
		
		
	</div>

<?php print $closure; ?>
</body>
</html>