<?php

 /******************************************************************************
  * Ubercart hooks                                                             *
  ******************************************************************************/

 /**
  * Implementation of hook_uc_price_handler().
  */
 function lotus_discounts_uc_price_handler() {
   return array(
     'alter' => array(
       'title' => t('Lotus Discount price handler'),
       'description' => t('Adds discounts to lotus product prices.'),
       'callback' => 'lotus_discounts_price_handler_alter',
     ),
   );
 }

 function lotus_discounts_price_handler_alter(&$price_info, &$context, &$options) {
   global $user;
   static $prices = array();
   
   //echo "the context type: ".$context['type']."</br>";
   
   // give user initial discount on item:

   if(!$context['subject']['offer']){ // if its not an offer apply discount
      $account = user_load($user->uid);
      
      $disc_1 = $price_info['price'] - ($price_info['price'] * ($account->profile_discount_1 / 100));
      $disc_2 = $disc_1 - ($disc_1 * ($account->profile_discount_2 / 100));
      $disc_3 = $disc_2 - ($disc_2 * ($account->profile_discount_3 / 100));
     
      $price_info['price'] = round($disc_3,2);
  
       switch ($context['type']) {
     
    
        case 'product_version':
      
          $loaded_cart = uc_cart_get_contents(); // get the cart to check against items
      
          foreach($loaded_cart as $cart_item){
            if($context['subject']['sku'] == $cart_item->model && $cart_item->qty >= $cart_item->version_imballo){ 
              // check that the item is in the cart and it meets the imballo for discount
              $price_info['price'] = round($price_info['price'] * 0.9, 2); // 10% discount
            }
        
          }
        break;
        
        case 'product_version_all_imballo':
              
              if(!in_array("consumer_level_2",$account->roles)){ // check if user is an agent to see prices without discounts
                $price_info['price'] =  round($price_info['price'] * 0.9, 2); // 10% discount
               }
        
        break;
        
        case 'cart_product_version':
      
         
            if($context['subject']['qty'] >= $context['subject']['imballo']){ 
              // check that the item is in the cart and it meets the imballo for discount
              if(!in_array("consumer_level_2",$account->roles)){ // check if user is an agent to see prices without discounts
                $price_info['price'] =  round($price_info['price'] * 0.9, 2); // 10% discount
               }
            }
        
        
        break;
        
        
        case 'order_product_version' :
            
            
            //echo "<pre>";
           // print_r($price_info['qty']);
            
           // echo "</pre>";
            //
            //echo $context['subject']['node']->product_versions[$context['subject']['product']->model]->imballo;
            
              if($price_info['qty'] >= $context['subject']['node']->product_versions[$context['subject']['product']->model]->imballo){ 
               // check that the item is in the cart and it meets the imballo for discount
                $price_info['price'] = round($price_info['price'] * 0.9, 2); // 10% discount
                //echo "cool";
              }
           
              
        break;
        
        
        case 'line_item' :
           /* echo "price info: <pre>";
            print_r($price_info);
            echo "</pre>";
            
            echo "context info: <pre>";
            print_r($context);
            echo "</pre>";*/
            //$context['subject']['order']->products
            //$price_info['price'] = 0;
        break;
        
        case 'order_product_page':
         if($context['qty'] >= $context['subject']['node']->product_versions[$context['subject']['product']->model]->imballo){ 
           // check that the item is in the cart and it meets the imballo for discount
           $price_info['price'] = round($price_info['price'] * 0.9, 2); // 10% discount
         }
        break;
        
    
         default:
           // Nothing to do.
          // return;
          break;
       }
       // Alter the price given in place.
 
   }
   
   //echo "the disp item: <pre>";
   //print_r($account);
   //echo "</pre>";
   
 }

