<?php
function custom_cart_form_alter(&$form, $form_state, $form_id) {
if ($form_id == 'uc_cart_view_form') {

//Here I just remove the title of the image column
$form['items']['#columns']['desc']['#value'] = 'cool';

//Now I am moving around the columns by adjusting the weight
$form['items']['#columns']['image']['weight'] = 0;
$form['items']['#columns']['desc']['weight'] = 1;
$form['items']['#columns']['qty']['weight'] = 2;
$form['items']['#columns']['total']['weight'] = 3;
$form['items']['#columns']['remove']['weight'] = 4;

}
}
?>